setup.py

Massive fix. Update the `setup.py` profile to the proper README extension. Currently pip install doesn't work because of this bug.

Update setup to reflect README.rst

---

CHANGELOG.rst
docs/conf.py
proplot/subplots.py
proplot/tests/test_journals.py

@lukelbd, this PR adds the AAAS journal specs to the `proplot.subplots()` command. It also has a few minor fixes:
* Move the journal specs table to the header and change name to `JOURNAL_SPECS` following PEP (https://www.python.org/dev/peps/pep-0008/#constants).
* Fix try/except clause in `subplots()` that was causing certain journal specs to break.
* Add `pytest` for all journal specs as a template for future testing.
* Update changelog and add capability in docs to link from changelog to PR/issue threads.
This is a great simple example of pytest's power. I created the test then ran pytest and found consistent errors in certain subsets of the dictionary (`TypeError` vs. `ValueError`). Once you get pytest implemented into Travis CI, this will run automatically on PRs and then you have no …

Add AAAS journals to subplot command

---

proplot/axes.py

This is a *temporary* solution to #54. It requires redefining the wrappers on the `CartopyAxes` class. In the future this will be fixed because all wrappers will be implemented as decorators, and the `super().pcolormesh` will call the `GeoAxes` version.

Temporary bugfix

---

proplot/wrappers.py

If the long_name attribute of an xarray is available, it must be used for labels instead of the standard_name.

Make sure that long_name has priority over standard_name

---

.pre-commit-config.yaml
CHANGELOG.rst
docs/axis.ipynb
docs/colors_fonts.ipynb
proplot/axes.py
proplot/axistools.py
proplot/styletools.py
proplot/wrappers.py

This PR improves the "dual" axis scale feature, makes the `xminorticks`/`yminorticks` `Axes.format` "toggle" always use the *default* minor locator for the minor scale, cleans up `_ScaleBase`, changes the default `symlog` subs and linthresh, and fixes the default `LogitScale` formatters and locators.
Edit: It also fixes various bugs associated with non-linear "parent" axis scales and "dual" axes.

Axis scale improvements

---

proplot/axes.py
proplot/rctools.py
proplot/subplots.py

This backend fixes various buggy behavior observed with the `%matplotlib qt` console backend. It also permits "tight" layout with the `nbAgg` backend -- since auto figure resizing is impossible with `nbAgg`, we just carry out the algorithm with fixed figure dims.

Preprocessor improvements

---

.gitignore
CHANGELOG.rst
docs/conf.py
docs/configuration.rst
docs/environment.yml
proplot/axes.py
proplot/axistools.py
proplot/rctools.py
proplot/styletools.py
requirements.txt

This improves reading/parsing of `.proplotrc` -- YAML is no longer required, we now parse just like in `matplotlibrc`. It also fixes an issue from #91 that removed the .proplotrc file display from the [website documentation](https://proplot.readthedocs.io/en/latest/configuration.html?highlight=axes.prop_cycle#the-proplotrc-file). Also adds some related changes: the `gridminor` props are now *children* of the `grid` props (so changing the latter also changes the former), and some minor bug fixes.

.proplotrc changes and related improvements

---

proplot/axes.py
proplot/styletools.py
proplot/wrappers.py

This repairs issues displaying `ListedColormap`s (i.e. color cycles) with `show_cycles` where colors are omitted and color levels are inordinately small/large. Instead of using `imshow`, we just use `colorbar`.
It is accomplished by passing `loc='_fill'` to the command. In the future I may expose this options to users (rename it to `loc='fill'`) so they can "fill" an arbitrary axes with `ax.colorbar(loc='fill')` but retain proplot's `colorbar_wrapper` features.

Use ax.colorbar for show_cmaps and show_cycles

---

CHANGELOG.rst
docs/configuration.rst
docs/usage.rst
proplot/__init__.py
proplot/rctools.py

Resolves #112 and removes the various `ipython` funcs. The `ipython_autoreload` and `ipython_autosave` funcs were unrelated to the goals of proplot and should have been included, and trying to change the backend at runtime was confusing for new users and impossible to get right in the case of `jupyter console`.

Remove ipython funcs

---

CHANGELOG.rst
proplot/axes.py
proplot/styletools.py
proplot/wrappers.py

This PR will permit *descending* colorbar levels. This is not restoring a native matplotlib feature; it is a new proplot feature. I'm adding this simply because I wanted it for one of my plots.
The following example demonstrates how this works for both evenly spaced and unevenly spaced levels:
```python
import proplot as plot
import numpy as np
data = np.random.rand(20, 20).cumsum(axis=0)
for levels in (
np.arange(0, 15, 1)[::-1],  # with Normalizer
[15, 10, 5, 2, 1, 0],  # with LinearSegmentedNorm
):
f, ax = plot.subplots()
ax.pcolormesh(data, levels=levels, colorbar='b')
```

Permit descending colorbar levels

---

CHANGELOG.rst
proplot/axes.py
proplot/wrappers.py

Resolves #103. This bug was caused by my `standardize_1d` and `standardize_2d` functions, which automatically applied `IndexFormatter` when they detected coordinate arrays of the `'object'` datatype (while this usually implies strings, it turns out cftime arrays are also of `'object'` datatype).
I am now more careful about how the standardize functions handle coordinates. The `IndexFormatter` is applied only for string arrays, and the centers-to-edges and edges-to-centers functions only work with *numeric* (non-datetime, non-string) coordinates.

Improve standardize_[12]d handling of diverse coordinate datatypes

---

CHANGELOG.rst
proplot/ticker.py

This fixes two `AutoFormatter` issues, where it would sometimes ignore locale-specific settings (i.e. `,` for decimal point instead of `.`) and the algorithm that corrects non-zero values formatted as zeros sometimes failed. It also adds `AutoFormatter` features to `SimpleFormatter`. It also fixes an issue where proplot would ignore the `rc['axes.unicode_minus']` setting.

AutoFormatter fixes

---

proplot/wrappers.py

Very small PR that fixes issue where unnamed pandas `Index`es were not used for automatically generated legends.

Auto legend fix

---

proplot/wrappers.py

Fixes #135 while preserving the `standardize_1d` usage that lets users pass 1d x vectors with 2d y arrays.

Fix issue with 2d scatter arguments

---

proplot/colors.py
proplot/constructor.py

I thought this was fixed in #149 but there were still some issues when merging `PerceptuallyUniformColormap`s with `LinearSegmentedColormap`s. This fixes them, and fixes an issue where base `matplotlib.Colormap` classes could not be passed through the `Colormap` constructor.

Fix issue with merging mixed colormap types

---

CHANGELOG.rst
proplot/wrappers.py

Fixes #130 but preserves the bar-grouping capability.

Fix grouped bar plots with datetime64 x coords

---

proplot/axes/base.py
proplot/wrappers.py

Fixes #136 and makes heatmap grid boxes square by default, just like `Axes.imshow` makes image pixels square by default.
It was a really simple error (2 line fix) -- basically proplot was interpreting the "index" as x coordinates and the "columns" as y coordinates (i.e. shape `(x, y)`). While this makes sense intuitively, it is incorrect for 2D plotting commands like `contour`, `pcolor`, and `heatmap`, which expect arrays to be shaped like `(y, x)`. It didn't show up in the examples because I happened to only test with dataframes with equal dimensions.

Fix standardize_2d issue with pandas dataframes

---

CHANGELOG.rst
docs/configuration.rst
docs/environment.yml
docs/projections.py
proplot/axes/geo.py
proplot/constructor.py
proplot/internals/__init__.py
proplot/internals/defaults.py
proplot/scale.py
proplot/wrappers.py

Resolves #21 and resolves #148. This PR will add support for cartopy 0.18. Some attribute names were deprecated that proplot uses internally, several bugs were fixed (so proplot's bug fix monkey patches are no longer necessary), and a new bug was introduced that required a new bug fix monkey patch.
This PR offers support for cartopy's `LongitudeFormatter` and `LatitudeFormatter` formatters, and uses `LongitudeLocator` and `LatitudeLocator` to determine longitude and latitude gridline locations by default, unless the user specifies some custom gridline interval/gridline locations. It also adds `rc['geogrid.rotatelabels']` and `rc['geogrid.labelpad']` rc settings.

Add support for cartopy v0.18

---

.pre-commit-config.yaml
.travis.yml
CHANGELOG.rst
docs/1dplots.py
docs/2dplots.py
docs/api.rst
docs/axis.py
docs/colorbars_legends.py
docs/colormaps.py
docs/conf.py
docs/cycles.py
docs/projections.py
docs/why.rst
proplot/__init__.py
proplot/axes/__init__.py
proplot/axes/base.py
proplot/axes/cartesian.py
proplot/axes/geo.py
proplot/axes/plot.py
proplot/axes/polar.py
proplot/colors.py
proplot/constructor.py
proplot/demos.py
proplot/figure.py
proplot/ui.py
proplot/utils.py
proplot/wrappers.py

Resolves #144. Now `ax.scatter()` accepts the exact same keyword arguments used to generate a `DiscreteNorm` as methods like `ax.contourf()` and `ax.pcolormesh()` -- if it detects that you passed an array of data values for the `c` argument.

Support DiscreteNorm in scatter plot colorbars

---

docs/1dplots.py
proplot/axes/base.py
proplot/axes/plot.py

This PR fixes a bug where parametric plot colorbar levels did not reflect the amount of "interpolation" between colors set by the `interp` keyword argument. It also permits making parametric plots with 3 positional arguments, which is more analogous to `scatter`:
```python
m = ax.parametric(x, y, c)  # new call signature, like ax.scatter(x, y, c)
m = ax.parametric(x, y, values=c)  # old verbose call signature
```

Parametric plot fixes

---

proplot/axes/base.py
proplot/axes/cartesian.py
proplot/axes/geo.py
proplot/figure.py
proplot/ui.py

Fixes #127 by reworking the axis sharing algorithm. This also fixes a related bug I noticed in the online documentation examples. This should be the last PR before I release version 0.6.0.

Fix axis sharing bugs

---

CHANGELOG.rst
docs/basics.py
docs/projections.py
proplot/colors.py
proplot/constructor.py
proplot/demos.py
proplot/utils.py

This permits passing non-scalar values to `LinearSegmentedColormap.set_alpha` and adds `to_rgba` and `to_xyza` to go along with `to_rgb` and `to_xyz`.

Permit setting opacity gradations with Colormap.set_alpha and add new to_rgba functions

---

proplot/axes/base.py

Resolves #133. You can now make `ax.inset_axes` with arbitrary projections, with the exact same syntax used to delcare projections in `plot.subplots()`. The default inset axes projection is the same as the parent axes projection. When the projections differ, "zoom" lines are disabled by default.

Support arbitrary projections for inset_axes

---

CHANGELOG.rst
docs/axis.py
proplot/axes/cartesian.py
proplot/constructor.py
proplot/ticker.py

Resolves #170. This should (really) be the last PR before version 0.6. It adds a "scientific notation" formatter and adds it to the examples on the website.

Add scientific notation formatter

---

proplot/axes/plot.py

I've just tried to add the feature I was talking about in https://github.com/lukelbd/proplot/issues/217, here is an adaptation of the example from https://proplot.readthedocs.io/en/latest/1dplots.html#Box-plots-and-violin-plots:
```python
import proplot as plot
import numpy as np
import pandas as pd
N = 500
state = np.random.RandomState(51423)
data = state.normal(size=(N, 5)) + 2 * (state.rand(N, 5) - 0.5) * np.arange(5)
data = pd.DataFrame(
data,
columns=pd.Index(['a', 'b', 'c', 'd', 'e'], name='xlabel')
)
fig, axs = plot.subplots(ncols=2, axwidth=2.5)
axs.format(grid=False, suptitle='Boxes and violins demo')
colors = ['gray5', 'pink5', 'violet5', 'blue5', 'teal5']
ax = axs[0]
obj1 = ax.boxplot(
data, lw=0.7, marker='x', fillcolor=colors, medianlw=1, mediancolor=colors, …
```

Support color lists for boxplots and violins

---

CHANGELOG.rst
proplot/axes/base.py
proplot/config.py
proplot/constructor.py
proplot/demos.py
proplot/figure.py
proplot/gridspec.py
proplot/internals/rcsetup.py
proplot/ticker.py

Fixes #248. Addresses errors + warnings encountered with matplotlib >= 3.4.0.

Fix matplotolib 3.3.0--3.4.0 regressions

---

CHANGELOG.rst
docs/basics.py
docs/projections.py
proplot/figure.py
proplot/internals/rcsetup.py

Originally I enforced the default behavior `rc['savefig.transparent'] = True` to make saved figure backgrounds transparent by default. This can be nice when putting plots on slides, posters, or websites with different light-colored backgrounds.
However, with the rising popularity of "dark modes" (on Github, macOS, twitter, etc.), this behavior more often results in users trying to read black text on dark backgrounds, and can be extremely frustrating and confusing. It also results in saved PDFs (which always show against white backgrounds) looking different from saved PNGs.
This PR reverts proplot to the more sensible default behavior of `rc['savefig.transparent'] = False`.

Return default savefig transparency to False

---

WHATSNEW.rst
proplot/axes/base.py
proplot/axes/plot.py
proplot/figure.py
proplot/internals/rcsetup.py

Resolves #198. Proplot supports more than one legend per subplot. However this means that each `legend()` call creates a brand new legend -- sometimes one on top of another. This was confusing to new users (IIRC there's a closed issue floating around) and broke external packages that rely on one legend per subplot (#198).
This PR does the best of both worlds. Proplot still supports multiple legends, but not on top of each other. If you call `legend()` more than once with the same *location* `loc` (or without `loc`, implying the same default location), proplot
will  either 1) replace the previous legend (if `queue=False`, the default) or 2) add handles to a "queue" (if `queue=True`). This "queueing"  option was previously only available in the wrapper functions, which didn't make sense. …

Refactor legend+colorbar internals, support "queueing" and location-based replacements

---

proplot/gridspec.py
proplot/ui.py

This would add the feature of https://github.com/lukelbd/proplot/issues/64, the ability to set `hspace` between all rows, `wspace` between all columns, or both, based on the calculated maximum value in ProPlot's layout routine.
I am not sure if this follows what you were suggesting in [this comment](https://github.com/lukelbd/proplot/issues/64#issue-522492491). It seems to work, but the gridspec's idea of `hspace` and `wspace` don't seem to match how the figure shows up (see my example, maybe I am printing the wrong thing).
See in action [here](https://gist.github.com/zmoon92/3da69fc1754cc6faddd523497d363828).

Tight layout options

---

WHATSNEW.rst
docs/1dplots.py
docs/_static/custom.css
docs/axis.py
docs/basics.py
docs/configuration.rst
docs/cycles.py
docs/fonts.py
docs/insets_panels.py
docs/projections.py
docs/subplots.py
docs/why.rst
proplot/axes/base.py
proplot/axes/cartesian.py
proplot/axes/geo.py
proplot/axes/plot.py
proplot/axes/polar.py
proplot/colors.py
proplot/config.py
proplot/constructor.py
proplot/demos.py
proplot/figure.py
proplot/internals/docstring.py
proplot/internals/rcsetup.py
proplot/internals/warnings.py
proplot/scale.py
proplot/ui.py

Resolves #194 (and #229). This is another one of those big "refactor" PRs. There are already a couple of them in the recent commit history -- I've been trying to make `plot.py` more organized, modular, and, well... less of a clusterf*ck. This will be the final one before the imminent v0.7 release. Here are some notes:
* The canonical order for 1D plotting wrappers is now switched from `plot_specific_wrapper` --> `standardize_1d` -->  ... to `standardize_1d` --> `plot_specific_wrapper` --> ... . This way I don't have to individually parse positional arguments for each `plot_specific_wrapper`. Now, the `plot_specific_wrapper`s are all smaller -- they just add keywords and support `negpos` "negative-positive" plots. Previously I had to put wrappers *before* `standardize` to convert keywords …

Final improvements to 1D plotting wrappers

---

docs/1dplots.py
docs/2dplots.py
docs/api.rst
docs/axis.py
docs/basics.py
docs/colorbars_legends.py
docs/colormaps.py
docs/colors.py
docs/configuration.rst
docs/cycles.py
docs/faq.rst
docs/fonts.py
docs/insets_panels.py
docs/projections.py
docs/subplots.py
docs/usage.rst
docs/why.rst
proplot/axes/base.py
proplot/axes/geo.py
proplot/axes/plot.py
proplot/axes/polar.py
proplot/colors.py
proplot/config.py
proplot/figure.py
proplot/scale.py
proplot/tests/test_journals.py
proplot/ticker.py
proplot/ui.py
proplot/utils.py

Resolves #139. This switches the recommended import statement from `import proplot as plot` to `import prolot as pplt` throughout the documentation and examples, in agreement with the poll winner.

Plot to pplt

---

proplot/axes/plot.py

I get a syntax error using the current version because several functions in plot.py using tuple unpacking while also returning multiple objects. It's resolved by unpacking inside a tuple

return tuples in plot.py

---

WHATSNEW.rst
proplot/axes/base.py
proplot/internals/rcsetup.py

Currently, `abc` does not consider the custom text. A provision can be made to incorporate that. Multiple titles can be incorporated in the `format`. I know there are ways that the functions may not be even needed. However, it is for the sake of consistency and making the user end code simple.
```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
abc=('A','B','1','2','a','b'), abcloc='ul',
xticks='null', yticks='null', facecolor='gray5',
xlabel='x axis', ylabel='y axis',
)
```
```python
import proplot as pplt
fig = pplt.figure(space=0, refwidth='10em')
axs = fig.subplots(nrows=3, ncols=2)
axs.format(
urtitle=('Title 1', 'Title 2', 'Test 1', 'Test2', 'Exp1', 'Exp2'),
xticks='null', yticks='null', facecolor='gray5', …
```

 adding custom abc and multiple titles #294

---

docs/basics.py

The current "The basics" section contains example codes that save figure to user's home directory.
I suggest we save to figure to where the example code is run instead to make life a bit easier for people who learn proplot by copying/pasting to Jupyter notebook.

Save to local instead of user directory in tutorial

---

.pre-commit-config.yaml
WHATSNEW.rst
ci/environment.yml
proplot/axes/base.py
proplot/axes/geo.py
proplot/axes/plot.py
proplot/internals/inputs.py

This will finally, finally, add robust image comparison testing to proplot using `pytest-mpl`.

Add pytest-mpl tests

---

setup.cfg

Why not do a point release with just this fix, so at least ProPlot is useable by `pip install`ers until you get a fix out?

Specify maximum matplotlib dependency

---

requirements.txt
setup.cfg

**proplot** package is an exciting as well as powerful package. Thanks for all the hard work (@lukelbd). I am maintaining this package in the Alpine Linux ecosystem.
I recommend you add numpy to the list of dependencies for correctness. Some files import this package.

Add numpy to the list of dependencies
